import struct

FORMATO_REQUISICAO = "! 4i"
TAMANHO_REQUISICAO = struct.calcsize(FORMATO_REQUISICAO)

FORMATO_RESPOSTA = "! i 15s"
TAMANHO_RESPOSTA = struct.calcsize(FORMATO_RESPOSTA)

SERVIDOR_IP = "127.0.0.1"
SERVIDOR_PORTA = 5000
